# Generated by Django 4.0.2 on 2022-03-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Query',
            field=models.CharField(default='', max_length=500),
        ),
    ]
